spring.application.name=demo
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/database_name
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.time-zone=Europe/Kyiv

jwt.secret-key="GwtY1yzKwOYQ/e4xyQLCE8kE7n9Kx/m+UB4VuIgFJzs="
jwt.expiration-time=7257600000
spring.profiles.active=dev

management.endpoints.web.exposure.include=health